Hospital Portal/Models/HospitalPortal.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HospitalDBContext : DbContext
    {
        public HospitalDBContext()
            : base("name=HospitalDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_MstHospital> tbl_MstHospital { get; set; }
    
        public virtual ObjectResult<sp_SearchHospital_Result> sp_SearchHospital(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchHospital_Result>("sp_SearchHospital", searchKeyWordParameter);
        }
    
        public virtual ObjectResult<tbl_MstHospital> SearchHospital(string searchKeyWord)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_MstHospital>("SearchHospital", searchKeyWordParameter);
        }
    
        public virtual ObjectResult<tbl_MstHospital> SearchHospital(string searchKeyWord, MergeOption mergeOption)
        {
            var searchKeyWordParameter = searchKeyWord != null ?
                new ObjectParameter("SearchKeyWord", searchKeyWord) :
                new ObjectParameter("SearchKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_MstHospital>("SearchHospital", mergeOption, searchKeyWordParameter);
        }
    }
}

Hospital Portal/Models/HospitalPortal.Designer.cs
// T4 code generation is enabled for model 'C:\Users\AmanVaish\source\repos\Hospital Potal\Hospital Portal\Models\HospitalPortal.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Hospital Portal/Models/HospitalPortal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Hospital Portal/Models/sp_SearchHospital_Result.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Portal.Models
{
    using System;
    
    public partial class sp_SearchHospital_Result
    {
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
    }
}

Hospital Portal/Models/tbl_MstHospital.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MstHospital
    {
        public int HospitalId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
    }
}

Hospital Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hospital_Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Hospital Portal/Controllers/HospitalController.cs
using Hospital_Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Hospital_Portal.Controllers
{
    public class HospitalController : Controller
    {
        // GET: Hospital
        public ActionResult Index()
        {
            HospitalDBContext dBContext = new HospitalDBContext();
            List<tbl_MstHospital> hospitalList = dBContext.tbl_MstHospital.ToList();
            return View(hospitalList);
        }
        [HttpPost]
        public ActionResult Index(string HospitalName)
        {
            HospitalDBContext dBContext = new HospitalDBContext();
            return View(dBContext.SearchHospital(HospitalName));
        }
        
        public async Task<ActionResult> HospitalDetails(int HospitalId)
        {
            ViewBag.PageName = "HospitalDetails";
            HospitalDBContext dBContext = new HospitalDBContext();
            return View(dBContext.tbl_MstHospital.Find(HospitalId));
        }
    }
}

Hospital Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hospital Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hospital Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Hospital Portal/Views/Hospital/HospitalDetails.cshtml
@model Hospital_Portal.Models.tbl_MstHospital

@{
    ViewBag.Title = "HospitalDetails";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card ">
                <img src="https://thumbs.dreamstime.com/b/medical-concept-hospital-medical-concept-hospital-buildings-ambulances-smooth-style-155129154.jpg" alt="Image" style="width:100%">
                <div class="container">
                    <h4><b>@Html.DisplayFor(item => item.Name)</b></h4>
                    <p>City: @Html.DisplayFor(item => item.City)</p>
                    <p>Email: @Html.DisplayFor(item => item.Email)</p>
                    <p>Mobile: @Html.DisplayFor(item => item.Mobile)</p>
                    <p>Description: @Html.DisplayFor(item => item.Description)</p>
                </div>
            </div>
        </div>
    </div>

</div>

Hospital Portal/Views/Hospital/Index.cshtml
@model IEnumerable<Hospital_Portal.Models.tbl_MstHospital>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<style>
    .bar {
        margin: 0 auto;
        padding: 0px 0px 0px 40px;
        border-radius: 30px;
        border: 1px solid #dcdcdc;
    }

        .bar:hover {
            box-shadow: 1px 1px 8px 1px #dcdcdc;
        }

        .bar:focus-within {
            box-shadow: 1px 1px 8px 1px #dcdcdc;
            outline: none;
        }

    .searchbar {
        padding: 0px 0px 0px 25px;
        margin: 0px;
        height: 40px;
        width: 60%;
        border: 1px solid #dcdcdc;
        border-radius: 35px 0px 0px 35px;
        font-size: 16px;
        outline: none;
    }

    .fa fa-search {
        float: right;
    }
    .btn {
        height: 40px;
        margin-top: -9px;
        border: 1px solid #dcdcdc;
        border-radius: 0px 35px 35px 0px;
        outline: none;
    }
</style>

<div class="container">
    @using (Html.BeginForm("Index", "Hospital", FormMethod.Post))
    {
        <div class="row justify-content-center">

            <div class="col-lg-6">
                @Html.TextBox("HospitalName", "", new { @class = "searchbar", @PlaceHolder = "Search Hospital", @Title = "Search" })
                @*<input class='searchbar' type='text' PlaceHolder='Search' title='Search'>*@
                <button class="btn btn-info btn-lg" type="submit">Search Hospital</button>

            </div>
        </div>
    }
        <br>
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {
            <div class="col-md-6">
                
                <div class="card ">
                    <img src="https://thumbs.dreamstime.com/b/medical-concept-hospital-medical-concept-hospital-buildings-ambulances-smooth-style-155129154.jpg" alt="Image" style="width:100%">
                    <div class="container">
                        <h4><b>@Html.DisplayFor(modelItem => item.Name)</b></h4>
                        <p>City: @Html.DisplayFor(modelItem => item.City)</p>
                        <p>Email: @Html.DisplayFor(modelItem => item.Email)</p>
                    </div>
                    @Html.ActionLink("View More >>", "HospitalDetails", new{ HospitalId = @item.HospitalId })
                </div>
                
            </div>
            }
        </div>

    
</div>

Hospital Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    @*<div class="container body-content">*@
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    @*</div>*@

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@
</body>
</html>